add task 1.1
hellianet/Clojure pull request #1
Opened 2022-12-06 18:55 UTC by hellianet

2022-12-07 12:34 UTC, shishkin-pavel requested changes
условия первой задачи немного изменены в наших группах, новые условия можно найти в первых сообщениях в телеге

2022-12-11 19:22 UTC, shishkin-pavel approved these changes
некоторые замечания есть, но давай дальше (а замечания лучше учесть в следующих лабах)

2022-12-11 19:22 UTC, shishkin-pavel commented on Lab1/task1.clj
> +  (fn [alphabet] (generate alphabet, '(()), n)))
а зачем это функция, возвращающая функцию?

2022-12-11 19:22 UTC, shishkin-pavel commented on Lab1/task1_3.clj
> +  (reverse (reduce (fn [acc, item](conj acc (f item)))
про это я тоже писал в телеге, что лучше бы тут использовать конкат но только после правильного понимания получившейся сложности мапа

2022-12-11 19:22 UTC, shishkin-pavel commented on Lab1/task1_4.clj
> +  (reduce (fn [acc i]
тут пришёлся бы очень кстати iterate

2022-12-13 14:38 UTC, hellianet commented on Lab1/task1.clj
> +  (fn [alphabet] (generate alphabet, '(()), n)))
Я это сделала, чтобы получать функцию, которая принимает только алфавит

2022-12-13 14:39 UTC, merged